name: CMake on multiple platforms

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-24.04, windows-latest]
        preset: [default, release]
        compiler: [gnu, llvm, msvc]
        include:
          - os: ubuntu-24.04
            build-deps:
              - libx11-dev
              - libxrandr-dev
              - libxcursor-dev
              - libxi-dev
              - libudev-dev
              - libgl1-mesa-dev
          - os: ubuntu-24.04
            compiler: gnu
            cxx: g++-14
          - os: ubuntu-24.04
            compiler: llvm
            packages:
              - libc++-18-dev
              - libc++abi-18-dev
        exclude:
          - os: windows-latest
            compiler: gnu
          - os: windows-latest
            compiler: llvm
          - os: ubuntu-24.04
            compiler: msvc

    env:
      CMAKE_WORKFLOW_PRESET: ${{ format('{0}{1}', matrix.preset, (matrix.compiler == 'llvm' && '-llvm' || '')) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - if: matrix.os == 'ubuntu-24.04' && matrix.build-deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ join(matrix.build-deps, ' ') }}

      - if: matrix.os == 'ubuntu-24.04' && matrix.packages
        run: sudo apt-get install -y ${{ join(matrix.packages, ' ') }}

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgJsonGlob: '**/vcpkg.json'

      - uses: lukka/run-cmake@v10
        if: matrix.cxx
        env:
          CXX: ${{ matrix.cxx }}
        with:
          workflowPreset: ${{ env.CMAKE_WORKFLOW_PRESET }}

      - uses: lukka/run-cmake@v10
        if: "!(matrix.cxx)"
        with:
          workflowPreset: ${{ env.CMAKE_WORKFLOW_PRESET }}
