name: CMake on multiple platforms

on:
  push: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-24.04, windows-latest]
        preset: [default, release]
        compiler: [gnu, llvm, msvc]
        include:
          - os: ubuntu-24.04
            compiler: gnu
            cxx: g++-14
          - os: ubuntu-24.04
            compiler: llvm
            package: 'libc++-18-dev libc++abi-18-dev'
        exclude:
          - os: windows-latest
            compiler: gnu
          - os: windows-latest
            compiler: llvm
          - os: ubuntu-24.04
            compiler: msvc


    env:
      CMAKE_WORKFLOW_PRESET: ${{ format('{0}{1}', matrix.preset, (matrix.compiler == 'llvm' && '-llvm' || '')) }}
    steps:
      - uses: actions/checkout@v4

      - if: matrix.os == 'ubuntu-24.04' && matrix.package
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.package }}

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-cmake@v10
        if: matrix.cxx
        env:
          CXX: ${{ matrix.cxx }}
        with:
          workflowPreset: ${{ env.CMAKE_WORKFLOW_PRESET }}

      - uses: lukka/run-cmake@v10
        if: matrix.cxx != true
        with:
          workflowPreset: ${{ env.CMAKE_WORKFLOW_PRESET }}
